replicaCount: 1

image:
  repository: ""
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

livenessProbe:
  path: /
  port: 8080
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3

readinessProbe:
  path: /
  port: 8080
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 2
  failureThreshold: 3

route:
  enabled: true
  host: ""
  tls: false

ingress:
  enabled: false

securityContext:
  runAsUser: null    # if null OpenShift will assign random UID
  runAsNonRoot: true
  fsGroup: null

podAnnotations: {}

serviceAccount:
  create: false
  name: null
