replicaCount: 1

image:
  repository: "image-registry.openshift-image-registry.svc:5000/test-attendance/frontend-app"
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

route:
  create: true
  host: ""
  tls: false

serviceAccount:
  create: false
  name: ""

# readiness/liveness probes (optional for static site)
readinessProbe:
  enabled: false

livenessProbe:
  enabled: false
