{{- $route := .Values.route | default dict }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "helm-chart.fullname" . }}
spec:
  to:
    kind: Service
    name: {{ include "helm-chart.fullname" . }}
  port:
    targetPort: http
{{- if $route.host }}
  host: {{ $route.host }}
{{- end }}
  tls:
    termination: {{ if $route.tls }}edge{{ else }}""{{ end }}