apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "helm-chart.fullname" . }}
spec:
  to:
    kind: Service
    name: {{ include "helm-chart.fullname" . }}
  port:
    targetPort: http
  host: {{ default nil .Values.route.host }}
  tls:
    termination: {{ if .Values.route.tls }}edge{{ else }}""{{ end }}